name: "Pull Request Sphinx Docs Check"

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  sphinx_docs_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10 env for sphinx...
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python3 requirements and run sphinx...
        uses: knicknic/os-specific-run@v1.0.4
        with:
          linux: cd /home/runner/work/purpleair_data_logger/purpleair_data_logger/ &&
                  python -m pip install --upgrade wheel &&
                  python -m pip install --upgrade setuptools &&
                  python -m pip install --upgrade pip &&
                  python -m pip install -r sphinx_docs_build/requirements.txt &&
                  python setup.py install --user &&
                  cd sphinx_docs_build &&
                  make html

      - uses: actions/upload-artifact@v3
        with:
          name: Upload HTML Documentation
          path: docs/