name: "Pull Request Sphinx Docs Check"

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "sphinx_docs_build/"
        build-command: "pip --disable-pip-version-check list --outdated --format=json | \
                        python3 -c "import json, sys; print('\n'.join([x['name'] for x in json.load(sys.stdin)]))" | \
                        xargs -n1 pip install -U; make html"

    - uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: docs/