name: "Pull Request Sphinx Docs Check"

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "sphinx_docs_build/"
          build-command: "make html"

      - uses: actions/upload-artifact@v3
        with:
          name: DocumentationHTML
          path: docs/